### ISSUE TITLE
java.lang.NullPointerException in the VFS API

### ISSUE THREAD

**Issue by gilbertovento** [bridje/bridje-framework#27]
Exception in thread "main" java.lang.NullPointerException
	at org.bridje.vfs.FileVfsSource.listFolders(FileVfsSource.java:59)
	at org.bridje.vfs.FileVfsSource.listFolders(FileVfsSource.java:34)
	at org.bridje.vfs.impl.PhysicalFolder.listFolders(PhysicalFolder.java:106)
	at org.bridje.vfs.impl.PhysicalFolder.listFolders(PhysicalFolder.java:89)
	at org.bridje.vfs.impl.AbstractResource.travel(AbstractResource.java:95)
	at org.bridje.vfs.impl.AbstractResource.travel(AbstractResource.java:98)
	at org.bridje.vfs.impl.AbstractResource.travel(AbstractResource.java:98)
	at org.bridje.vfs.impl.AbstractResource.travel(AbstractResource.java:98)
	at org.bridje.vfs.impl.PhysicalFolder.travel(PhysicalFolder.java:196)
	at org.bridje.examples.simple.config.Main.main(Main.java:34)

**Comment by gilbertovento** [comment]
I put a validation on after calling the File.listFiles method, becouse it may return null.
